// This file contains complete translations for all missing keys that were causing TypeScript errors
// It serves as a reference to manually complete the incomplete language translations

const missingKeysTemplate = {
  // Critical missing keys that are causing the most errors
  exercise1: "Exercise 1",
  exercise2: "Exercise 2", 
  marketAnalysis: "Market Analysis",
  percentageCalculation: "Percentage Calculation",
  trendCalculation: "Trend Calculation",
  customerSatisfaction: "Customer Satisfaction",
  statistics: "Statistics",
  averageValues: "Average Values",
  showCalculatedShares: "Show calculated shares",
  hideCalculatedShares: "Hide calculated shares",
  basicFormulaText: "Market Share = (Company Revenue / Total Industry Revenue) × 100",
  siriusRevenue: "Sirius Revenue",
  industryRevenue: "Industry Revenue", 
  marketShareTerm: "Market Share",
  calculateIncrease: "Calculate increase",
  percentageIncreaseFormula2: "Percentage Increase = (New Market Share - Old Market Share) / Old Market Share × 100",
  dataType: "Data Type",
  industryRevenueMio: "Industry (€ million)",
  siriusRevenueMio: "Sirius AG (€ million)",
  marketSharePercent: "Market Share (%)",
  increasePercent: "Increase (%)",
  stepByStepExplanation: "Step-by-step explanation:",
  step1: "Collect base data:",
  step1Description: "Industry revenue and Sirius AG revenue for each semester",
  step2: "Calculate market share per period:",
  step2Description: "(Sirius AG / Industry) × 100",
  step3: "Determine percentage increase:",
  step3Description: "Comparison with previous period",
  step4: "Interpret results:",
  step4Description: "Identify trends and developments",
  solutionAHide: "Hide solution a)",
  solutionBHide: "Hide solution b)",
  showCompleteAnalysis: "Show complete analysis",
  hideCompleteAnalysis: "Hide complete analysis",
  hadHighestMarketShare: "had the highest market share with",
  calculationExplanation: "Calculation explanation:",
  formula: "Formula:",
  marketShareFormulaSpecific: "Market Share = (Sirius AG Revenue / Industry Revenue) × 100",
  example: "Example for",
  meaning: "Meaning:",
  strongestMarketPosition: "This shows the strongest market position throughout the observation period.",
  largestPercentageIncrease: "The largest percentage increase occurred from",
  to: "to",
  withIncrease: "with an increase of",
  notAvailable: "Not available.",
  percentageIncreaseFormula: "Percentage Increase = (new value - old value) / old value × 100",
  calculation: "Calculation:",
  solutionALabel: "Solution a) Good and better",
  solutionBLabel: "Solution b) Satisfactory and worse", 
  solutionCLabel: "Solution c) Ecological aspects",
  goodAndBetter: "good and better",
  satisfactoryAndWorse: "satisfactory and worse",
  ecologicalAspects: "Ecological Aspects",
  customersWithAverage: "Customers with average grade",
  numberOfCustomers: "Number of customers with",
  haveRated: "have",
  rated: "rated",
  averageGrade: "Average grade", 
  ecoAverageGrade: "Eco average grade",
  analysis: "Assessment",
  overallAnalysisTitle: "📊 Overall analysis of customer survey",
  majorityOfCustomers: "Majority of customers",
  ratedGoodOrBetter: "rated the company good or better",
  onlyPercentage: "Only",
  gaveSatisfactoryOrWorse: "of customers gave satisfactory or worse ratings",
  ecoAspectsRated: "Ecological aspects were rated with",
  correspondTo: "rated - this corresponds to",
  recommendation: "Recommendation:",
  improveEcoAspects: "Improving ecological aspects could enhance overall satisfaction",
  ecoAspectsAlreadyGood: "Ecological aspects are already rated well",
  interpretation: "Interpretation:",
  totalCustomers: "Total number of customers:",
  sumOfRatings: "Sum of eco ratings:",
  allCustomersEcoRatings: "Eco ratings of all customers:",
  result: "Result:",
  noCustomers: "No customers",
  firstHalf: "1st Half",
  secondHalf: "2nd Half",
  showsStrongestPosition: "shows strongest market position",
  stepByStepAnalysis: "Complete step-by-step analysis", 
  methodicalApproach: "Methodical approach:",
  importantInsights: "Important insights:",
  highestMarketShare: "Highest market share:",
  calculateIncreaseRates: "Calculate increase rates:",
  percentageChanges: "Percentage changes between consecutive periods",
  meaningLargestGrowth: "This shows the largest relative growth leap in market share.",
  strongestIncrease: "Strongest increase:",
  trendAnalysis: "Trend analysis:",
  continuousGrowth: "Continuous market share growth observable over the observation period",
  businessRelevance: "Business relevance:",
  positiveMarketDevelopment: "Positive market development supports strategic business decisions",
  taskDescription: "Task description",
  ratingLegend: "Rating legend",
  customer: "Customer",
  function: "Function",
  performance: "Performance",
  eco: "Eco",
  price: "Price",
  average: "Average",
  summary: "Summary",
  surveyResults: "Customer survey results:",
  goodAndBetterShort: "Good and better",
  satisfactoryAndWorseShort: "Satisfactory and worse",
  ecoAverage: "Eco average",
  showsDynamicDevelopment: "Increase - shows most dynamic development",
  with: "with",
  gradeVeryGood: "very good",
  gradeGood: "good",
  gradeSatisfactory: "satisfactory",
  gradeAdequate: "adequate",
  gradeDeficient: "deficient",
  gradeInsufficient: "insufficient",
  gradeUnknown: "Unknown",
  gradeLabelVeryGood: "Very Good",
  gradeLabelGood: "Good",
  gradeLabelSatisfactory: "Satisfactory",
  gradeLabelAdequate: "Adequate",
  gradeLabelDeficient: "Deficient",
  gradeLabelInsufficient: "Insufficient",
  absoluteIncrease: "Absolute increase:",
  percentagePoints: "percentage points",
  dataCollection: "Data collection:",
  collectRevenueData: "Collecting revenue data for industry and Sirius AG over 6 semesters",
  calculateMarketShare: "Calculate market share:",
  applyFormula: "Apply formula: (Sirius AG / Industry) × 100 for each semester",
  identifyMaximum: "Identify maximum:",
  compareAllShares: "Compare all market shares to determine maximum value",
  collectBaseData: "Collect base data",
  showTableCustomer: "Show table",
  showSolutionCustomer: "Show solution",
  showOverallAnalysis: "📊 Show overall analysis"
};

// Languages that need completion: sy, ar, ru, pl, at, ch, nl, cz, sk, md
// Each language needs ALL of the keys above translated appropriately

console.log('Missing keys template created with', Object.keys(missingKeysTemplate).length, 'keys');
console.log('Languages needing completion: sy, ar, ru, pl, at, ch, nl, cz, sk, md');
console.log('All these keys need to be manually added to each incomplete language section.');
